<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'Описание игры',
    'About Go-Moku' => 'Описание игры Го-Моку',
    'Action' => 'Действие',
    'Active' => 'Активно',
    'Answer' => 'Ответ',
    'Auth Key' => 'Ключ аутентификации',
    'Available Users:' => 'Пользователи:',
    'Confirmed' => 'Подтверждено',
    'Delete' => 'Удалить',
    'Eng' => 'Eng',
    'First player' => 'Первый игрок',
    'From' => 'От пользователя',
    'From user' => 'От пользователя',
    'Game' => 'Игра',
    'Game ID' => 'Game ID',
    'Game Turns' => 'Ходы в игре',
    'GameCenter' => 'Игровой центр',
    'Go-Moku Game' => 'Игра Го-Моку',
    'Go-Moku is ancient chinese game.' => 'Го-Моку - это древняя китайская игра. Её русский вариант - "крестики-нолики".',
    'ID' => 'ID',
    'Incorrect username or password.' => 'Неправильное имя или пароль.',
    'Invitations to you:' => 'Приглашения для вас:',
    'Invite again' => 'Повторить приглашение',
    'Invite this user' => 'Пригласить этого пользователя',
    'Language' => 'Язык',
    'Login' => 'Войти',
    'Logout ({username})' => 'Выйти ({username})',
    'Message' => 'Приглашение',
    'Next turn' => 'Следующий ход',
    'No' => 'Отклонить',
    'Not answered yet' => 'Ещё не отвечено',
    'Not your turn' => 'Не ваш ход',
    'Password' => 'Пароль',
    'Play' => 'Играть',
    'Previous turn' => 'Предыдущий ход',
    'Rating' => 'Рейтинг',
    'Rejected' => 'Отозвать',
    'Second player' => 'Второй игрок',
    'Show' => 'Показать',
    'To' => 'Кому',
    'To user' => 'Кому',
    'Username' => 'Имя',
    'Wait for answer' => 'Ожидайте ответа',
    'Winner' => 'Победитель',
    'Yes' => 'Принять',
    'You win {winner_name} ! Yor rating +1 !' => 'Вы выиграли {winner_name} ! Ваш рейтинг +1 !',
    'Your active games:' => 'Ваши активные игры:',
    'Your invitations:' => 'Ваши приглашения:',
    'Your previous games:' => 'Ваши предыдущие игры:',
    'Your rating: {rating}' => 'Ваш рейтинг: {rating}',
    '{username} is winner!' => '{username} победил!',
    'Ру' => 'Ру',
];
